<a href="https://colab.research.google.com/github/2101327/0912/blob/main/NumPyReplay2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np
x=np.array([1.0*i for i in range(1,6)])
print(x)
x=np.array([i for i in range(1,4)])
print(x)
print(type(x))
my_list1=[i for i in range(1,6)]
my_array1=np.array(my_list1)
my_list2=10*my_array1
my_lists=[my_list1,my_list2]
my_lists
my_array2=np.array(my_lists)
my_array2

[1. 2. 3. 4. 5.]
[1 2 3]
<class 'numpy.ndarray'>


array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [16]:
a=np.array([i for i in range(1,5)])
a.shape
b=np.array([[1,2],[3,4]])
b.shape

(2, 2)

In [17]:
x=np.arange(10)
print(x)
x=np.arange(1,10).reshape(3,3)
y=x
print(x)
print(y)
print(x+y)
print(x-y)
print(x*y)

[0 1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [18]:
sample_array=np.arange(10)
print(sample_array)
sample_array2=sample_array.reshape(2,5)
print(sample_array2)
sample_array3=np.array([[1,2,3],[4,5,6]])
sample_array4=np.array([[7,8,9],[10,11,12]])
print(np.concatenate([sample_array3,sample_array4],axis=1))
print(np.hstack((sample_array3,sample_array4)))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [19]:
print(np.concatenate([sample_array3,sample_array4],axis=0))
print(np.vstack((sample_array3,sample_array4)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [20]:
sample_array=np.arange(10)
print(sample_array)
print(sample_array+5)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]


In [21]:
n1=np.array([i for i  in range(1,6)])
print(n1)
np.ndim(n1)
n1.shape
n2=np.array([[1,2],[3,4],[5,6]])
print(n2)
print(n2.ndim)

[1 2 3 4 5]
[[1 2]
 [3 4]
 [5 6]]
2


In [22]:
my_li1=[-1,4]
my_li2=[3,2]
my_li3=[2,5]
my_li4=[0,1]
my_lists=[my_li1,my_li2,my_li3,my_li4]
my_array3=np.array(my_lists)
my_array3

array([[-1,  4],
       [ 3,  2],
       [ 2,  5],
       [ 0,  1]])