<a href="https://colab.research.google.com/github/2101327/0912/blob/main/%E3%83%A2%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB0920.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#モジュール

In [ ]:
import math
math.pi

3.141592653589793

In [ ]:
math.e

2.718281828459045

In [ ]:
math.tan(math.pi/4)

0.9999999999999999

In [ ]:
math.cos(math.pi)

-1.0

In [ ]:

import math
math.pi*math.e

8.539734222673566

In [ ]:
import numpy as np

In [ ]:
a=np.array([i for i in range(1,11)])

In [ ]:
a.reshape([5,2])

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
a=np.zeros((5,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
l=list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
l[4:8]

[4, 5, 6, 7]

In [ ]:
l[::-1]

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [ ]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[2:8]

array([2, 3, 4, 5, 6, 7])

In [ ]:
a[2:8:2]

array([2, 4, 6])

In [ ]:
a[3:6]=100
print(a)

[  0   1   2 100 100 100   6   7   8   9]


In [ ]:
a[2:8:2]=100
a

array([  0,   1, 100, 100, 100, 100, 100,   7,   8,   9])

In [ ]:
a=np.arange(12).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a=np.arange(20).reshape((5,4))

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
a[2:2]

array([], shape=(0, 4), dtype=int64)

In [ ]:
print(a[2:2])

[]


In [ ]:
a[2:,1:3]

array([[ 9, 10],
       [13, 14],
       [17, 18]])

In [ ]:
a[2:,1:3].shape

(3, 2)

In [ ]:
a=np.arange(12).reshape(3,4)

In [ ]:
a[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a[1:,1:3]=[100,200]
a

array([[  0,   1,   2,   3],
       [  4, 100, 200,   7],
       [  8, 100, 200,  11]])

In [ ]:
a[1:,1:3]=[[100,200],[300,400]]

In [ ]:
a

array([[  0,   1,   2,   3],
       [  4, 100, 200,   7],
       [  8, 300, 400,  11]])

In [ ]:
a=np.arange(12).reshape(3,4)

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a[1:,::2]

array([[ 4,  6],
       [ 8, 10]])

In [ ]:
a[:1,::3]

array([[0, 3]])

In [ ]:
a[:1]

array([[0, 1, 2, 3]])

In [ ]:
a[:2,::3]

array([[0, 3],
       [4, 7]])

In [ ]:
a[1:,::2]=[[100,200],[300,400]]

In [ ]:
a

array([[  0,   1,   2,   3],
       [100,   5, 200,   7],
       [300,   9, 400,  11]])