<a href="https://colab.research.google.com/github/2101327/0912/blob/main/%E3%83%A2%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB0920.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#モジュール

In [ ]:
import math
math.pi

3.141592653589793

In [ ]:
math.e

2.718281828459045

In [ ]:
math.tan(math.pi/4)

0.9999999999999999

In [ ]:
math.cos(math.pi)

-1.0

In [3]:

import math
math.pi*math.e

8.539734222673566

In [4]:
import numpy as np

In [9]:
a=np.array([i for i in range(1,11)])

In [11]:
a.reshape([5,2])

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [14]:
a=np.zeros((5,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
l=list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
l[4:8]

[4, 5, 6, 7]

In [17]:
l[::-1]

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [18]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a[2:8]

array([2, 3, 4, 5, 6, 7])

In [20]:
a[2:8:2]

array([2, 4, 6])

In [22]:
a[3:6]=100
print(a)

[  0   1   2 100 100 100   6   7   8   9]


In [23]:
a[2:8:2]=100
a

array([  0,   1, 100, 100, 100, 100, 100,   7,   8,   9])

In [24]:
a=np.arange(12).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
a[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])